name: olist_ds
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=1.26.4
  - pandas=2.2.1
  - matplotlib=3.8.3
  - seaborn=0.13.2
  - scikit-learn=1.4.1
  - xgboost=2.0.3
  - lightgbm=4.3.0
  - imbalanced-learn=0.12.0
  - nltk=3.8.1
  - wordcloud=1.9.3
  - mlflow=2.11.1
  - flask=3.0.2
  - sqlalchemy=2.0.28
  - plotly=5.19.0
  - pytest=8.0.2
  - geopy=2.4.1
  - joblib=1.3.2
  - tqdm=4.66.2
  - python-dotenv=1.0.1
  - pip
  - pip:
      - shap==0.45.0
      - sqlite3worker==1.1.7
      - waitress==3.0.0